### ISSUE TITLE
example_file components are disconnected and at the origin of the canvas

### ISSUE THREAD

**Issue by DanielAbalde** [joelhi/g3-gh#1]
Hi there! Thanks for wrapping this library, it looks promising!

I just opened the example_file.gh and I got this:
![wsdfsadf](https://user-images.githubusercontent.com/14053237/146458671-c9093e8a-e460-4531-b482-fd79768fa6e9.png)

It looks like some components are disconnected and at the origin of the canvas, no idea why it can happens but looks like an ID issue.. IDK, but if you want to try to reinstantiate new components to replace them, I can check the new file.

**Comment by DanielAbalde** [comment]
It may be a (de)serialization issue. Maybe you saved the file with some `bool Write(GH_IWriter writer)` and `bool Read(GH_IReader reader)` code and then you updated these code later, so GH saved an old format but the components expect the new format and serialization fails but GH is able to load it to the canvas (but without its pivot location).

**Comment by joelhi** [comment]
Hey! Thanks for noticing.

As you say, I also think it's a deserialization issue. Haven't opened that file in a while, but will have a look tomorrow morning.

Cheers!

**Comment by joelhi** [comment]
The issue was that I forgot to call the base Read/Write functions when deserializing with custom data. Silly.

Made the changes and made a new release [here](https://github.com/joelhi/g3-gh/releases/tag/v1.1-beta)
Let me know if you have a chance to try it out.

Cheers!

**Comment by DanielAbalde** [comment]
Yes it works as expected now. Thanks!
Could you release a .zip with the .gha, .dll and example files next time, please? It would be easier distribution.
